package ch.cern.todo.core.application.task.exception;

import ch.cern.todo.core.application.exception.NotFoundException;

public class TaskNotFoundException extends NotFoundException {

    public TaskNotFoundException() {}

}
